name: Build and Deploy Quire Site

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows pushing to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Quire CLI
        run: pnpm install -g @gettypubs/quire

      - name: Install project dependencies
        run: pnpm install

      - name: Build the site
        run: quire build

      - name: Deploy built files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.AZT_GITHUB_TOKEN }}
          publish_dir: ./
          exclude_glob: |
            .github/**
            node_modules/**
            content/**
            theme/**
            README.md
            package*.json
            quire.config.js
            data/**
            scripts/**
